### ISSUE TITLE
Multiple transactions in a row

### ISSUE THREAD

**Issue by rtsisyk** [stegos/stegos#304]
A meta ticket to track all issues need to be fixed in order to allow multiple successive transactions to be created in the single round.

**Wallet**:

- [ ] [Research how wallet can identify successful transaction](https://github.com/stegos/stegos/issues/326)
- [x] [Decouple wallet implementation from NodeService](https://github.com/stegos/stegos/issues/301)
- [ ] [Allow wallet to create multiple transactions in a row](https://github.com/stegos/stegos/issues/302)

**Mempool**:

- [ ] Add a queue for orphan transactions.
- [x] [Decouple mempool implementation from NodeService](https://github.com/stegos/stegos/issues/299)
- [x] [Prune transactions from mempool by UTXO ID](https://github.com/stegos/stegos/issues/300)
- [ ] [Allow transactions to use UTXOs from mempool transactions](https://github.com/stegos/stegos/issues/217)
- [ ] (Optional) [Order transactions in mempool](https://github.com/stegos/stegos/issues/303)

**Comment by rtsisyk** [comment]
Not actual anymore.
