### ISSUE TITLE
Test Plan for Transactions

### ISSUE THREAD

**Issue by rtsisyk** [stegos/stegos#391]
**Encoding/Decoding:**

- [x] Invalid protobuf packet
- [ ] <s>Missing mandatory fields</s> - impossible to test.

**Basic Validation:**

- [x] Invalid monetary balance - UNIT  TEST
- [x] Invalid signature - UNIT TEST
- [x] One input (PaymentUTXO), fee, no outputs (should work) - UNIT TEST
- [x] No inputs, one output (error) - UNIT TEST
- [x] No inputs, no outputs (error) - UNIT TEST
- [x] StakeUTXO as input - UNIT TEST
- [x] StakeUTXO as output - UNIT TEST
- [x] Negative fee - UNIT TEST
- [x] Zero fee - UNIT TEST
- [x] Mutated gamma - UNIT TEST
- [x] Duplicate input inside tx - UNIT TEST
- [x] Duplicate output inside tx - UNIT TEST
- [x] Fee < expected - UNIT TEST
- [x] Fee > expected (should work) - UNIT TEST
- [x] Missing or spent input in blockchain - UNIT TEST
- [x] Claimed input in mempool - UNIT TEST
- [x] Output hash collision in blockchain  - UNIT TEST
- [x] Output hash collision in mempool - UNIT TEST
- [x] TX hash is unique - UNIT TEST
- [x] Invalid unstake - UNIT TEST

**PaymentUTXO Validation:**

- [x] Mutated recipient  - UNIT TEST
- [x] Invalid bullet proofs - UNIT TEST
- [x] Zero amount (should work) - UNIT TEST
- [x] Negative amount  - UNIT TEST
- [x] Truncated payload - UNIT TEST

**Stake UTXO Validation:**
 
- [x] Mutated recipient  
- [x] Zero or negative amount  - UNIT TEST
- [x] Truncated payload
- [x] Stake locking - UNIT TEST
- [ ] <s>Less than 3 node staked</s>

**Mempool:**

- [x] Partial pruning (prune a part of transaction without removing a whole tx) - UNIT TEST
- [ ] <s>Overflow</s> - https://github.com/stegos/stegos/issues/468
