### ISSUE TITLE
Test Plan for Blockchain Database

### ISSUE THREAD

**Issue by rtsisyk** [stegos/stegos#394]
**Encoding/Decoding:**

- [ ] Invalid protobuf packet
- [ ] Missing mandatory fields
- [ ] Duplicate witnesses

**Basic Processing:**

- [ ] Invalid version
- [ ] Invalid epoch 
- [ ] Invalid timestamp
- [ ] Invalid multisignature
- [ ] Bitmap is too large
- [ ] Multisignature has 2/3 
- [ ] Invalid SealedBlockMessage signature
- [ ] Sender of SealedBlockMessage is not leader
- [ ] Already registered / duplicate hash
- [ ] Missing previous block

**Key Block:**

- [ ] No witnesses (error)
- [ ] Leader is not witness (error)
- [ ] Genesis block validation

**Monetary Block:**

- [ ] Invalid monetary balance
- [ ] One input (PaymentUTXO), fee, no outputs (should work)
- [ ] One input (DataUTXO), no outputs (should work) 
- [ ] No inputs, one output (should work)
- [ ] No inputs, no outputs (should work)
- [ ] StakeUTXO as input
- [ ] StakeUTXO as output
- [ ] Mutated gamma
- [ ] Invalid input_range_hash
- [ ] Invalid output_range_hash
- [ ] Min/max of  monetary_adjustment
- [ ] Duplicate input inside block
- [ ] Duplicate output inside block
- [ ] Missing input
- [ ] Output hash collision in blockchain 
- [ ] Global monetary balance
- [ ] TX exists in mempool
- [ ] Re-created block has the same hash as proposed
- [ ] Genesis block validation
- [ ] Block with zero fee

Plus UTXO-specified tests from https://github.com/stegos/stegos/issues/391:

**PaymentUTXO:**

- [ ] Mutated recipient 
- [ ] Invalid bullet proofs
- [ ] Zero amount (should work)
- [ ] Negative amount 
- [ ] Truncated payload

**Stake UTXO:**
 
- [ ] Mutated recipient  
- [ ] Zero or negative amount  
- [ ] Amount is less than PAYLOAD_FEE (error)
- [ ] Truncated payload
- [ ] Stake locking

**Other**:

- [ ] Invalid serialized Merkle Tree
- [ ] Serialization of pruned Merkle Tree
- [ ] Blockchain::output_by_hash() for a missing utxo
- [ ] Blockchain::outputs_by_hashes()
- [ ] Blockchain::block_by_hash
- [ ] Blockchain::height()
- [ ] Error handling in Blockchain::register_key_block()
- [ ] Error handling in Blockchain::register_key_block()
- [ ] KeyBlock::new_from_header()
- [ ] Repalce panic!() with unreachable!() in tests

**Comment by rtsisyk** [comment]
The real coverage is next to 100%. Anyway, let's check this list.
