### ISSUE TITLE
Crypto

### ISSUE THREAD

**Issue by rtsisyk** [stegos/stegos#4]
- [x] Elliptic Curves Arithmetics
- [x] Choose Elliptic Curve Generators
- [x] Choose Hashing Algo (SHA256?) 
- [x] BulletProofs and Pedersen Commitments
- [x] Distributed Randomness (RandHound)

**Comment by rtsisyk** [comment]
Done.
