### ISSUE TITLE
Test plan for VRF

### ISSUE THREAD

**Issue by vldm** [stegos/stegos#444]
**DDoS/DoS Resistance:**
- [x] Invalid encoding
- [x] Too many tickets (Can we run OOM?)

**Consistency**
- [x] Take into acount LOWER_BOUND (2/3 of tickets)
- [x] Check group changing. (in unit test)
- [x] Change view_change, and retry on fail

**Fork resistance:**
- [x] Tickets from future
- [x] Duplicate tickets
- [x] Not enought tickets
- [x] Restart on timeout
- [ ] Recover view_change on node restart.
