### ISSUE TITLE
Test plan for Chain load and Persistency (disk storage and network load)

### ISSUE THREAD

**Issue by vldm** [stegos/stegos#447]
# Test cases:
## Testing recovery:
- [ ] Regular restart single node.
- [ ] Restart 1/3- node and wait for recover. (system should keep working, and 1/3- nodes should recover in background)
- [ ] Restart 50% of nodes for short time, (system should recover during VRF).
- [ ] Restart 50% of nodes for long time (N hours) (system should recover at next N hours).
- [ ] Hard faults (process kill, and system reboot should still make system recoverable) at block write.
- [ ] Hard faults at recover.
- [ ] Fault during chain load.
## Message processing during chain load:
- [ ] Invalid message received as response.
- [ ] Invalid blocks received in response.
- [ ] Invalid request.
- [ ] Not full response received;.
- [ ] Too many requests to single node.
- [ ] Tracking a list of nodes that can send responses.

### Consensus
- [ ] validators before and after restart the same
- [ ] facilitator the same
- [ ] leader the same
### ValueShuffle/TxPool
- [ ] Transaction that is processed on ValueShuffle, should keep processing after restart.
- [ ] pool formation should keep runing

For chain load the same integrity checks should be done, all state except timers should be compared with other node states. **Timers should be handled separately.**

**Comment by vldm** [comment]
In #752 Roman wrote, that we need test for case:
> 1 validator was restarted with database clearing.
Rest of nodes run into different view_change forks (some of view_change messages was not delivered to some of nodes)
