### ISSUE TITLE
Slashing

### ISSUE THREAD

**Issue by rtsisyk** [stegos/stegos#51]
- [x] Design slash logic.
- [ ] Implement Slash pool
- [ ] [Warrant transactions/MonetaryAdjustment](https://github.com/stegos/stegos/issues/316)

**Comment by vldm** [comment]
We decide to make slashlike in albatross consensus.
Any leader that try to create fork (more than one block at height) should be punished.
As proof of punishment conflicted block should be aplied into blockchain.

**Comment by rtsisyk** [comment]
Slashing has been implemented.
