### ISSUE TITLE
Staking/Unstaking

### ISSUE THREAD

**Issue by rtsisyk** [stegos/stegos#53]
A meta-ticket for slashing/unslashing issues.

- [x] [Research Staking/Unstaking/Slashing/Jackpot](https://github.com/stegos/stegos/issues/277)
- [x] [Implement Escrow UTXO](https://github.com/stegos/stegos/issues/272)
- [x] [REPL commands for staking/unstaking](https://github.com/stegos/stegos/issues/315)
- [x] [REPL command to unstake all money](https://github.com/stegos/stegos/issues/350)
- [x] [Re-generate genesis block to include stakes](https://github.com/stegos/stegos/issues/348)
- [x] [Include fees into `unstake` amount](https://github.com/stegos/stegos/issues/349)
- [x] [Validate block timestamp](https://github.com/stegos/stegos/issues/317)
- [x] [Hold stakes for 1 month](https://github.com/stegos/stegos/issues/318)
- [x] [Rename EscrowUTXO to StakeUTXO](https://github.com/stegos/stegos/issues/351)

**Comment by rtsisyk** [comment]
Splited slashing into a separate ticket: https://github.com/stegos/stegos/issues/51

**Comment by rtsisyk** [comment]
Done
