### ISSUE TITLE
New Node Bootstrap

### ISSUE THREAD

**Issue by rtsisyk** [stegos/stegos#61]
A meta-ticket for new node boostrap.

Proposed algorithm:

- Subscribe for sealed block messages
- Queue all received sealed blocks
- Find a source node for bootstrap
- Request initial blockchain state from the source node
- Apply initial state
- Apply queued sealed blocks

**Issues**:

- [x] [Update to libp2p 0.1](https://github.com/stegos/stegos/issues/322)
- [x] [Unicast messaging](https://github.com/stegos/stegos/issues/161)
- [x] [Select a source node for bootstrap and establish connection](https://github.com/stegos/stegos/issues/319)
- [x] [Initial blockchain state transfer](https://github.com/stegos/stegos/issues/320)
- [x] [Final blockchgain state transfer](https://github.com/stegos/stegos/issues/321)

**Comment by rtsisyk** [comment]
Closed by #410
