### ISSUE TITLE
Consensus epoch refactoring plan

### ISSUE THREAD

**Issue by vldm** [stegos/stegos#611]
The main plan, is to modify our consensus mechanisms, acording to [albatros paper](https://arxiv.org/pdf/1903.01589.pdf).

Full flow is described in #605

- [x] Add `vrf result` to `KeyBlock`. https://github.com/stegos/stegos/issues/608
- [x] Add `view_change` to `KeyBlock`. #612 
- [x] Remove vrf tickets
- [x] Checks that random is created using `VRF(previous_random, LeaderKey)` #605
