### ISSUE TITLE
Minimal Working Persistency

### ISSUE THREAD

**Issue by rtsisyk** [stegos/stegos#8]
A meta-ticket to track minimal working persistency for blocks. 

The core concept is simple - keep existing in-memory database and all indexes, duplicate all blocks to RocksDB when they are registered, use RocksDB to recover in-memory database on the start. That is it.

Please note that in-memory storage and indexes are not removed. No changes here. RocksDB will be used to store a copy of in-memory data and to recover this data on the start. RocksDB should contain full unpruned blocks, where as in-memory storage can keep blocks pruned. Pruning is not reflected to ocksDB. Indexes are not duplicated to RocksDB. Pruning is performed during recovery from the disk.

The proposed implementation is pretty simple and straightforward, but have obvious limitations:

- Blockchain is limited to the size of RAM
- Blocks are stored un-pruned on the disk
- Recovery procedure can be slow

These limitations are well-known and will be addressed by further epics. Let's get minimal working persistency first.

**Plan**:

- [ ] [Integrate Rust RocksDB bindings to stegos_blockchain](https://github.com/stegos/stegos/issues/58)
- [x] [Move Block serialization from stegos_node to stegos_blockchain](https://github.com/stegos/stegos/issues/60)
- [ ] [Duplicate registered blocks to RocksDB](https://github.com/stegos/stegos/issues/57)
- [ ] [Implement recovery from RocksDB](https://github.com/stegos/stegos/issues/59)
